"""init

Revision ID: 95eefe6f668c
Revises: 
Create Date: 2024-11-10 15:30:28.011751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95eefe6f668c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('mcc', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('operationAmount', sa.Integer(), nullable=True),
    sa.Column('currencyCode', sa.Integer(), nullable=True),
    sa.Column('commissionRate', sa.Integer(), nullable=True),
    sa.Column('receiptId', sa.String(length=250), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_description'), 'statements', ['description'], unique=False)
    op.create_index(op.f('ix_statements_mcc'), 'statements', ['mcc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statements_mcc'), table_name='statements')
    op.drop_index(op.f('ix_statements_description'), table_name='statements')
    op.drop_table('statements')
    # ### end Alembic commands ###
